/**
 * Zod transform factory for motion model inputs.
 *
 * Creates a schema that accepts our internal camelCase format
 * (numeric duration, imageUrl, aspectRatio) and transforms it to
 * the API's snake_case format with correctly-typed duration values,
 * then validates with the generated Zod schema.
 *
 * All formatting rules are derived from the JSON Schema (generated by
 * @hey-api/schemas) — no Zod introspection needed.
 */

import { z } from 'zod';

import type { MotionJSONSchema } from './endpoint-map';

import { getLogger } from '@/lib/observability/logger';

const logger = getLogger(['openstory', 'motion', 'motion-transform']);

// ---------------------------------------------------------------------------
// JSON Schema readers
// ---------------------------------------------------------------------------

type JSONProp = Record<string, unknown>;

/** Unwrap anyOf wrapper to find a variant matching a key. */
function unwrapAnyOf(prop: JSONProp, key: string): JSONProp | undefined {
  if (key in prop) return prop;
  if ('anyOf' in prop && Array.isArray(prop.anyOf)) {
    return prop.anyOf.find((s) => key in s);
  }
  return undefined;
}

/** Extract valid duration values from the JSON Schema duration property. */
export function getDurationValues<T extends MotionJSONSchema>(
  schema: T
): (string | number)[] {
  const props = schema.properties;
  if (!('duration' in props)) return [];
  const dur = props.duration as JSONProp;

  const withEnum = unwrapAnyOf(dur, 'enum');
  if (withEnum && Array.isArray(withEnum.enum))
    return withEnum.enum.filter((v) => !Number.isNaN(numericOf(v)));

  const withRange = unwrapAnyOf(dur, 'minimum');
  if (withRange) {
    const min = Number(withRange.minimum);
    const max = Number(withRange.maximum);
    return Array.from({ length: max - min + 1 }, (_, i) => min + i);
  }

  return [];
}

/** Extract maxLength from the prompt property, handling anyOf wrappers. */
function getPromptMaxLength(schema: MotionJSONSchema): number | undefined {
  const props = schema.properties;
  if (!('prompt' in props)) return undefined;
  return Number(unwrapAnyOf(props.prompt, 'maxLength')?.maxLength ?? undefined);
}

/** Find the image URL field name (start_image_url or image_url). */
function getImageUrlField(schema: MotionJSONSchema): string | undefined {
  const props = schema.properties;
  if ('start_image_url' in props) return 'start_image_url';
  if ('image_url' in props) return 'image_url';
  return undefined;
}

// ---------------------------------------------------------------------------
// Transform helpers
// ---------------------------------------------------------------------------

const zMotionInput = z.looseObject({
  prompt: z.string(),
  duration: z.number().optional(),
  imageUrl: z.string().optional(),
  aspectRatio: z.string().optional(),
});

export function numericOf(v: string | number): number {
  return typeof v === 'number' ? v : parseFloat(v);
}

export function snapTo(
  n: number,
  values: readonly (string | number)[]
): string | number {
  const numeric = values.filter((v) => !Number.isNaN(numericOf(v)));
  return numeric.reduce((prev, curr) =>
    Math.abs(numericOf(curr) - n) < Math.abs(numericOf(prev) - n) ? curr : prev
  );
}

function truncatePrompt(prompt: string, maxLength: number): string {
  if (prompt.length <= maxLength) return prompt;

  const paragraphs = prompt.split('\n\n');
  let result = '';
  for (const paragraph of paragraphs) {
    const candidate = result ? `${result}\n\n${paragraph}` : paragraph;
    if (candidate.length <= maxLength) {
      result = candidate;
    } else {
      break;
    }
  }
  if (!result) return prompt.slice(0, maxLength - 3) + '...';

  logger.warn(
    `Prompt truncated from ${prompt.length} to ${result.length} chars`
  );
  return result;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Create a Zod transform from an API schema + its JSON Schema metadata.
 *
 * Accepts camelCase input (prompt, duration, imageUrl, aspectRatio),
 * transforms to the API's snake_case format, and validates.
 */
export function motionTransform<T extends z.ZodObject<z.ZodRawShape>>(
  apiSchema: T,
  jsonSchema: MotionJSONSchema
) {
  const durationValues = getDurationValues(jsonSchema);
  const imageUrlField = getImageUrlField(jsonSchema);
  const maxPromptLength = getPromptMaxLength(jsonSchema);

  return zMotionInput.transform((input): z.infer<T> => {
    const { imageUrl, aspectRatio, duration, prompt, ...rest } = input;
    const raw = {
      ...rest,
      prompt: maxPromptLength
        ? truncatePrompt(prompt, maxPromptLength)
        : prompt,
      ...(imageUrl && imageUrlField && { [imageUrlField]: imageUrl }),
      ...(aspectRatio && { aspect_ratio: aspectRatio }),
      ...(duration !== undefined &&
        durationValues.length > 0 && {
          duration: snapTo(duration, durationValues),
        }),
    };
    return apiSchema.parse(raw);
  });
}
