/**
 * Sequence Elements Schema
 * Per-sequence user-uploaded reference images (logos, product shots, screenshots)
 * referenced in scripts by uppercase token.
 */

import { type InferInsertModel, type InferSelectModel } from 'drizzle-orm';
import {
  index,
  integer,
  snakeCase,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import { generateId } from '../id';
import { sequences } from './sequences';

const VISION_STATUSES = [
  'pending',
  'analyzing',
  'completed',
  'failed',
] as const;
export type ElementVisionStatus = (typeof VISION_STATUSES)[number];

export const sequenceElements = snakeCase.table(
  'sequence_elements',
  {
    id: text()
      .$defaultFn(() => generateId())
      .primaryKey()
      .notNull(),
    sequenceId: text()
      .notNull()
      .references(() => sequences.id, { onDelete: 'cascade' }),
    // Original filename as uploaded, used to derive the token.
    uploadedFilename: text({ length: 500 }).notNull(),
    // Uppercase token used to reference this element in scripts (e.g. "LOGO", "BOTTLE").
    // Must be unique within a sequence.
    token: text({ length: 100 }).notNull(),
    // Visual description generated by the vision LLM.
    description: text(),
    // Short slug tag used in prompts for consistency (e.g. "red-hex-logo").
    consistencyTag: text(),
    // Storage
    imageUrl: text().notNull(),
    imagePath: text().notNull(), // R2 key
    // Vision analysis status
    visionStatus: text()
      .$type<ElementVisionStatus>()
      .default('pending')
      .notNull(),
    visionError: text(),
    visionGeneratedAt: integer({ mode: 'timestamp' }),
    // First appearance in script (populated during scene-split reconciliation)
    firstMentionSceneId: text(),
    firstMentionText: text(),
    firstMentionLine: integer(),
    // Timestamps
    createdAt: integer({ mode: 'timestamp' })
      .$defaultFn(() => new Date())
      .notNull(),
    updatedAt: integer({ mode: 'timestamp' })
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (table) => [
    index('idx_sequence_elements_sequence_id').on(table.sequenceId),
    uniqueIndex('sequence_elements_sequence_token_key').on(
      table.sequenceId,
      table.token
    ),
  ]
);

export type SequenceElement = InferSelectModel<typeof sequenceElements>;
export type NewSequenceElement = InferInsertModel<typeof sequenceElements>;

export type SequenceElementMinimal = Pick<
  SequenceElement,
  'id' | 'token' | 'description' | 'imageUrl' | 'consistencyTag'
>;
