import type { KnipConfig } from 'knip';

export default {
  entry: [
    'src/router.tsx',
    'src/routes/**/*.{ts,tsx}', // file-based routes
    'src/functions/**/*.ts', // createServerFn endpoints
    'scripts/**/*.ts',
    '.storybook/**/*.{ts,tsx}',
    'content-collections.ts', // content-collections build config (root)
    // MSW request mocks (registered by path, not statically imported).
    'src/lib/mocks/browser.ts',
    'src/lib/mocks/server.ts',
    // Swapped in by .storybook/server-stub-plugin.ts via a Vite alias (string
    // path), so knip can't trace them from an import.
    'src/lib/mocks/server-stub.ts',
    'src/lib/mocks/tanstack-start.ts',
    // Aliased for `cloudflare:workers` in .storybook/main.ts (string path).
    'src/lib/mocks/cloudflare-workers.ts',
  ],
  project: ['src/**/*.{ts,tsx}', 'scripts/**/*.ts'],
  ignore: [
    '**/*.gen.ts', // generated (routeTree.gen.ts, etc.)
    '**/*.stories.tsx', // analysed by the Storybook build, not the app graph
    '**/*.test.ts',
    // shadcn/ui: a vendored component library kept at full API surface on
    // purpose (managed by the shadcn CLI, not hand-pruned).
    'src/components/ui/**',
  ],
  ignoreDependencies: [
    // Tailwind plugin / PostCSS / Tailwind — used via CSS + @tailwindcss/vite, not imported.
    'tw-animate-css',
    'postcss',
    'tailwindcss',
    // Testing library — used in the vitest setup file.
    '@testing-library/jest-dom',
    '@testing-library/react',
    '@testing-library/user-event',
    // shadcn CLI.
    'shadcn',
    // Cloudflare Workers runtime modules (not npm packages).
    'cloudflare',
    // Build-time virtual module generated by @content-collections/vite.
    'content-collections',
    // Available transitively and imported directly (acceptable here):
    '@videojs/core', // via @videojs/react
    '@tiptap/extension-hard-break', // via @tiptap/starter-kit
    'html-dom-parser', // via html-react-parser
    'hast', // via the unified/rehype toolchain (types only)
    // Consumed only by the ignored shadcn src/components/ui/** library, so
    // knip can't see the usage — keep them out of the unused-deps report.
    '@radix-ui/react-alert-dialog',
    '@radix-ui/react-avatar',
    '@radix-ui/react-dialog',
    '@radix-ui/react-dropdown-menu',
    '@radix-ui/react-label',
    '@radix-ui/react-popover',
    '@radix-ui/react-scroll-area',
    '@radix-ui/react-separator',
    '@radix-ui/react-toggle',
    '@radix-ui/react-toggle-group',
    // Used in src/styles/global.css (@import / @plugin), not via a TS import.
    '@fontsource-variable/geist',
    '@tailwindcss/typography',
    // Used by the e2e mocks (e2e/ is outside knip's project scope).
    '@copilotkit/aimock',
    // Type package paired with the `diff` runtime dependency.
    '@types/diff',
  ],
  ignoreBinaries: [
    // CLI tools / shell builtins invoked from package.json scripts.
    'stripe',
    'printf',
    'open', // macOS URL/file opener (bun explorer)
  ],
} satisfies KnipConfig;
