// AUTO-GENERATED by scripts/generate-style-briefs.ts — do not edit by hand.
// One sample brief per style, derived from each style’s own description + config.

/**
 * Consumed by `briefForStyle` in `sample-videos.ts` (script/test graph only),
 * which knip doesn't trace — keep this `@public` so it isn't flagged as dead.
 * @public
 */
export const GENERATED_STYLE_BRIEFS: Record<string, string> = {
  'product-ad':
    "A woman's hands with neatly trimmed nails twist open a frosted-glass jar of peach-toned face cream on a sunlit marble bathroom shelf, then a fingertip presses into the dewy texture as warm afternoon light throws crisp shadows across the curling product label.",
  'real-estate':
    'A woman with sleek dark hair in cream silk loungewear walks barefoot across a sunlit travertine living room, pouring rosé at a marble island as late-afternoon beams stream through floor-to-ceiling windows, then steps onto a terrace silhouetted against a glowing sunset.',
  animatic:
    'A rough pencil-and-marker pre-vis frame of a young male knight with messy hair and a worn cloak drawing his sword and lunging forward at a looming dragon silhouette, the camera slowly pushing in as motion lines streak across the smudged paper-tone background.',
  corporate:
    'A woman with short dark hair in a navy blazer gestures toward a wall-mounted screen, walking a small team through a rising sales dashboard in a bright open-plan office before turning to camera with a confident smile as colleagues nod around the glass table.',
  'award-season':
    'An aging gray-bearded man in a worn brown cardigan sits at a dim kitchen table, hands trembling as he opens a faded letter, and the slow push-in catches a single tear rolling down his cheek as warm lamplight cuts through deep shadow.',
  documentary:
    'A weathered fisherman with grey stubble and a worn yellow raincoat hauls a dripping net of silver fish onto his small boat at dawn, the handheld camera bobbing with the waves as he wipes his brow and squints toward the misty harbor.',
  action:
    'A rugged male stunt driver in a torn leather jacket and buzzcut sprints from an exploding warehouse, vaults onto a speeding motorcycle, and weaves through shattering glass as the camera cranes overhead in saturated orange-and-teal firelight.',
  'rom-com':
    'A curly-haired woman in a yellow sundress laughs and chases after a man in a rolled-sleeve blue shirt down a sunlit cobblestone street, both clutching dripping ice cream cones as the camera glides alongside their playful sprint.',
  animated:
    'A grizzled male bounty hunter in a tattered crimson coat strides through a rain-slicked neon alley, then halts as a holographic wanted-poster flickers to life before him, its cold blue glow sweeping across his scarred, expressive face.',
  'neo-noir-thriller':
    'A grey-coated male detective with slicked-back hair steps from a rain-slicked alley into a neon-lit doorway, flicking his cigarette and turning sharply as venetian-blind shadows slide across his face under a tense Dutch-angle frame.',
  pastel:
    'A mustached bellhop in a powder-blue uniform and pillbox hat stands dead-center in a butter-yellow hotel lobby, ringing a brass desk bell three times before wheeling a cart stacked with mint and pink leather luggage straight toward the symmetrical camera.',
  'sci-fi-futuristic':
    'A short-haired male engineer in a sleek silver jumpsuit strides through a glowing spaceship corridor, sweeping his hand across a floating holographic display that ripples to life, as cool blue LED panels pulse and lens flares streak past a wide window revealing distant stars.',
  'horror-gothic':
    'A pale woman with long black hair in a tattered Victorian gown lifts a flickering candelabra and creeps down a crumbling cathedral corridor as shadows lurch across cracked stone walls, the camera tilting and slowly zooming toward a door that creaks open by itself.',
  'western-epic':
    "A weathered male gunslinger in a dusty long coat and wide-brimmed hat strides across a sunbaked frontier town's main street, then mounts his horse and rides toward the blazing low sun, kicking up swirling dust against long raking shadows.",
  'lo-fi-retro':
    'A young man in a wrinkled gray hoodie with messy brown hair laughs and waves a sparkler around at a backyard dusk gathering, the handheld phone wobbling as he turns toward friends while the blown-out lamp glows behind him.',
  'glossy-product-hero':
    'A sleek obsidian-black perfume bottle rotates slowly on a mirrored turntable against a sculpted gradient backdrop, its glass facets catching crisp specular highlights as a hyper-smooth dolly glides from wide silhouette into a macro reveal of the glowing gold brand mark.',
  'premium-lifestyle':
    'A woman with loose dark waves in an ivory linen robe steps onto a sun-soaked balcony, slowly pours espresso into a ceramic cup as steam rises, then lifts it to her lips while late-day light wraps her face and the camera racks focus from hand to her quiet smile.',
  'beauty-macro':
    'In slow-motion macro, a glass dropper releases a glowing amber serum that ribbons down its tip and pools on porcelain, then the camera pushes in as a fingertip glides a dewy peach cream across realistic poreed skin under soft luminous light.',
  'automotive-cinematic':
    'A glossy midnight-blue sports coupe carves through a winding mountain pass at golden hour, low raking sun skating across its painted flanks as an aerial drone tracks the car powering through sweeping curves while blue-hour sky and crushed shadows deepen behind it.',
  'fashion-editorial':
    "A tall female model in a structured emerald wool coat with slicked-back dark hair stands against a bare concrete wall under hard directional light, slowly turning her head toward camera as her hand brushes the coat's lapel before the lens dollies in on the fabric.",
  'luxury-still':
    'On a dark sculpted stone slab, a single hand-blown amber whisky bottle catches a soft window key as a slow macro push tracks across its glass shoulder, a single droplet of light sliding down while deep walnut shadow pools on the opposite side.',
  'food-beverage-hero':
    "In warm side-lit slow motion, a chef's hand pulls a glossy red tomato sauce across a white plate with the back of a spoon, then a macro probe lens dives past steam rising off a fresh pasta nest as a basil leaf drops onto the aged marble surface.",
  'tech-keynote':
    'On a dark seamless stage, a sleek silver smartphone rotates slowly center-frame as a glowing blue gradient orb pulses behind it, then floating UI fragments parallax outward in crisp white panels while the camera dollies in for the clinical hero reveal.',
  'fintech-explainer':
    'A young woman with curly dark hair in a cozy cream sweater taps her phone and exhales with a relieved smile in her warm sunlit apartment, then a measured push-in reveals her glass-card dashboard animating a soft accent bar as a savings goal fills.',
  'perfume-editorial':
    'In a spare sunlit room, a faceted amber perfume bottle rotates slowly on a marble ledge as backlit mist drifts past, then a woman with long dark hair in flowing ivory silk reaches into the haze, her fingertips brushing the glass as a sheer curtain billows behind her.',
  'watch-macro':
    "A polished steel diver's watch rotates slowly against a deep charcoal gradient as its blue second hand sweeps across the lacquered dial, then a macro probe lens glides in to reveal the engraved crown and brushed lugs catching a deliberate strip-light kicker.",
  'sportswear-motion':
    'A muscular male sprinter in a black compression top and crimson running shoes explodes from a starting block on wet neon-lit asphalt, sweat and water spray suspended in 240fps slow motion as the camera tracks low alongside his driving stride.',
  'alcohol-pour':
    "On a slate surface against a dark gradient backdrop, a single ice cube drops into a crystal tumbler and a stream of amber whisky pours in slow motion, splashing and swirling while backlight glows the liquid gold and the heritage bottle's label catches a deliberate kicker beside it.",
  'jewellery-rotation':
    "A platinum solitaire diamond ring rotates ultra-slowly on a black sculpted velvet plinth as pinpoint lights ignite fire across its facets, then a woman's manicured hand with soft pink polish glides in to lift the ring toward a luminous backlight.",
  'hospitality-lifestyle':
    'A woman in a flowing white linen robe with loose dark hair steps onto a sun-warmed terrace and slips slowly into an infinity pool that melts into the ocean horizon, the camera tracking past breakfast on crisp linen as soft golden light wraps the scene.',
  'white-background-studio':
    'On pure white seamless, a glossy cobalt-blue stainless steel water bottle rotates slowly through its front three-quarter beauty pass, then the camera glides into a macro detail pass tracking across the engraved logo and brushed metal cap under even, neutral softbox light.',
  'lifestyle-on-model':
    'A woman with loose brown waves in a cream knit sweater pulls a tan leather crossbody bag over her shoulder, adjusts the strap, and steps through a sunlit kitchen toward the door, soft daylight warming her face as she glances back.',
  'ugc-unboxing':
    "A woman's hands with chipped pink nail polish slice the packing tape on a cardboard box atop a coffee table, peel back crinkling tissue paper, and lift out a sleek skincare bottle into the handheld phone frame beside a plant and coffee mug.",
  'flat-lay-overhead':
    "Shot directly overhead on warm raw oak, a tan leather watch sits centered as a woman's hand with neutral nails slides a steaming espresso cup and a sprig of rosemary into frame, then folds a linen napkin while the camera slowly pushes in.",
  '360-turntable':
    'A sleek matte-black wireless over-ear headphone set rests centered on a motorized turntable against a soft gray gradient, rotating a smooth full 360 degrees at constant velocity under even three-point softbox lighting as a subtle rim light grazes its rotating earcups and headband.',
  'as-seen-on-phone':
    "A man's hand with a casual gray sleeve holds a phone over a sunlit kitchen counter, his thumb scrolling a vertical feed until a sleek matte-black water bottle snaps into frame, rotating slowly on screen as he taps to zoom into its macro detail.",
  'marketplace-listing':
    'A stainless steel insulated water bottle rotates slowly on a pure white background, its brushed metal surface catching even softbox light as the screw-top lid lifts off to reveal the threaded mouth, then settles back into a locked compliant hero frame.',
  'kitchen-counter-ugc':
    'A woman with messy dark bun and oversized green sweater scoops a heaping spoon of protein powder into a mug on her cluttered kitchen counter, then pours steaming water and stirs vigorously beside a half-cut lemon, daylight from the window glinting off the swirling drink as the phone micro-jitters.',
  'bathroom-counter-ugc':
    'A woman with damp wavy brown hair in a white tank top reaches into frame on a cluttered bathroom counter, pumps a dollop of cream serum into her palm beside a toothbrush and lit candle, then smooths it across her cheek as she glances into the mirror.',
  'returns-friendly-diagnostic':
    "On an even-lit white studio table, a man's hand lays a tan leather crossbody bag beside a steel tape measure, slides the tape to its 9-inch width, flips the bag to show stitching, then pushes in for a macro pass across the grained leather.",
  'packaging-close-up':
    'A macro probe lens glides slowly along the seam of a matte-black craft box as raking light sweeps across its embossed gold-foil logo, igniting the foil into a deliberate gleam before a fingertip lifts the sharp-edged ribbon and the lid parts to reveal grain-textured tissue.',
  'in-context-use':
    'A man with short dark hair in a grey flannel shirt zips an insulated cooler bag shut on a sunlit picnic blanket, lifts it to test the sturdy strap, then unzips it to reveal frosty drink cans still beaded with cold condensation.',
  'warm-vlog':
    'A young woman with messy auburn bun and oversized cream sweater sits cross-legged on her sofa talking warmly to camera, then leans forward to lift a steaming mug as her dog hops up beside her, fairy lights glowing behind plants and stacked books.',
  'ring-light-tutorial':
    'A woman with a dark high ponytail in a mustard sweater leans into her ring-lit desk, gesturing and smiling as she explains a skincare routine, then the shot cuts overhead to her hands pumping serum and pressing it onto her palm.',
  'podcast-clip':
    'A bearded male host in a charcoal sweater leans into his boom mic mid-laugh, gesturing toward a red-haired female co-host in a cream blazer who nods and taps the wood table as the locked two-shot slowly punches in for emphasis.',
  'street-interview':
    'On a busy downtown sidewalk, a young man with curly black hair and a green hoodie laughs and gestures as he answers an off-camera question into a visible handheld mic, the camera micro-shaking and reframing as passersby stream behind him.',
  'bedroom-confessional':
    'A young woman with messy dark hair in an oversized cream sweater sits cross-legged on her bed against the headboard, picks at a loose thread, then looks up into the camera and quietly speaks about the hardest year of her life as warm lamplight half-shadows her face.',
  'kitchen-tutorial':
    'A cheerful woman with curly brown hair tied back and a mustard apron leans toward the counter explaining her garlic butter pasta, then the overhead camera catches her hands tossing glistening noodles and showering grated parmesan over the steaming golden bowl.',
  'gym-selfie-cam':
    'A muscular man in a black tank top and backwards cap films a mirror selfie between sets, wiping sweat from his forehead before racking a loaded barbell and talking energetically to his phone about his pre-workout routine under bright gym LED.',
  'car-talk':
    'A bearded man in a gray hoodie grips the wheel and glances between the road and the dashboard camera, talking animatedly about his morning as sunlight flickers across his face and city traffic slides past the windshield behind him.',
  'walking-and-talking':
    'A young man with tousled brown hair, denim jacket and white tee strides briskly down a sunlit city sidewalk talking directly into the gimbal, gesturing toward the storefronts gliding past behind him before glancing over his shoulder at the busy crosswalk.',
  'reaction-cam':
    'A male creator with curly dark hair and a hoodie leans toward his desk mic, eyes widening and jaw dropping as he watches an inset clip, then throws both hands up and recoils back into his gaming chair while purple-and-teal LEDs glow behind him.',
  'bedtime-storybook':
    'A small round-cheeked brown bear cub in a patched blue nightcap tiptoes across a moonlit clearing, lifting a glowing paper lantern toward a sleepy owl as fireflies drift up through the painterly twilight trees and the camera slowly pushes in.',
  'saturday-morning-cartoon':
    'A goofy orange cartoon dog with floppy ears and a red bow tie skids around a corner chasing a runaway bouncing rubber ball, springs off a flat-painted fence with an exaggerated overshoot, then strikes a wide-eyed grin pose mid-air before tumbling into a pile of leaves.',
  claymation:
    'A round-bellied clay hedgehog with stubby legs and visible thumbprints waddles across a cardboard-and-moss tabletop diorama, then proudly plucks a wobbly red clay apple from a tiny tree, hugging it close under warm tungsten light.',
  'paper-cutout':
    'A paper-cutout fox puppet with orange scissored card fur and brad-jointed legs hops across a folded green paper meadow, nudging a layered cardboard sun higher up the sky as background hills slide past beneath the soft top-down key light.',
  'watercolour-fable':
    'A small russet fox kit, painted in soft watercolour washes on visible cotton paper, pads across a dewy meadow at dawn and pauses to nudge a dandelion, its seeds drifting upward in gentle parallax as the camera slowly pans.',
  'pop-up-book':
    'As the cream paper page lifts open, a hinged cut-paper fox with a red felt tail springs upright between staggered paper trees, and the camera slowly pushes in to discover a folding paper sun rising over the layered diorama.',
  'felt-and-yarn':
    'A round felt hedgehog puppet with button eyes and a knitted orange scarf waddles across a stitched green meadow, tugging a wobbling yarn-ball that unravels behind him, then pauses to wave a stubby paw up at fluttering felt butterflies.',
  'chalkboard-doodle':
    'On a dark green slate, white and pastel chalk lines draw themselves into a smiling sun and a sprouting seed, then a tiny hand-drawn watering can tips over to pour dotted chalk droplets as the seedling grows leaf by leaf, the camera pushing in through faint chalk-dust smudges.',
  'lo-fi-anime':
    'A teen girl with a short black bob and an oversized cardigan rests her forehead against a moving train window, fogging the glass with her breath and slowly drawing a small heart as warm magic-hour fields blur past in parallax outside.',
  'hand-drawn-picture-book':
    'A round-cheeked boy with a tuft of orange hair and a green striped shirt skips across a crayon-textured meadow chasing a giggling polka-dot butterfly, his arms waving as the scribbled flowers and paper-cream sky parallax gently behind him.',
  'rough-storyboard':
    'On warm paper-toned sketch, a broad-shouldered male detective in a rumpled trench coat and fedora, drawn in confident gestural pencil, shoves open a rain-streaked diner door and strides toward the counter, marker-wash shadows trailing his decisive forward motion.',
  'low-detail-blockout':
    'A featureless grey low-poly mannequin walks across an untextured greybox plaza, climbs three blocky primitive steps, and pushes open a simple box-geometry door as the single wide layout camera slowly tracks right to verify the staging under flat ambient shading.',
  'mood-only-frames':
    'A man in a long charcoal coat, dark hair backlit, stands silhouetted in dense amber fog as a slow push-in glides toward him and he lifts one hand, swirling the glowing mist while a hard rim of crimson light bleeds across the frame.',
  'black-white-previz':
    'In rich monochrome previz, a man in a long dark trench coat strides through a hazy warehouse as a hard key light throws his elongated shadow across the floor, the dolly tracking alongside him before craning up into volumetric beams.',
  'schematic-concept':
    'An isometric exploded diagram of a sleek wireless earbud and its charging case slowly drifts apart, dashed callout boxes and leader-line labels snapping into place around the battery, driver, and sensor as the camera holds steady then slowly zooms into the highlighted antenna callout.',
  'marker-rough':
    'A male barista with a messy bun and rolled-sleeve apron slides a steaming takeaway cup across a counter toward camera, rendered in bold flat marker tones on warm paper with a single orange accent, soft drop shadow beneath him, as the frame drifts gently right.',
  'greyscale-layout':
    'A male detective in a long silhouetted trench coat strides across a rain-slicked warehouse floor toward a tall window, his shadow stretching as the camera slowly drifts in, the whole frame rendered in blocked greyscale tonal values.',
  'intentionally-unfinished':
    "A red vintage convertible speeds along a coastal cliff road at golden hour, the fully-rendered car and asphalt cinematically lit while the ocean and sky remain rough pencil sketch on paper-tone, annotation scribbles reading 'add spray + lens flare' jittering over the half-drawn horizon as the car drives through frame.",
  'real-estate-listing':
    'A drone glides up over a sun-drenched two-story modern home with manicured green lawns at midday, then a smooth gimbal walk pushes through open glass doors into a bright, airy living room where warm light pours across level hardwood floors and styled furnishings.',
  'saas-product-demo':
    'A crisp project-management dashboard fills the screen as the cursor glides to drag a task card across columns and a push-in zoom annotates a live progress bar, then cuts to a friendly male narrator with short dark hair in a navy sweater gesturing confidently at his clean daylit desk.',
  'healthcare-patient-story':
    'A silver-haired man in a soft blue cardigan sits by a sunlit kitchen window, leaning in to speak warmly to camera about his recovery, his hands gesturing gently before he lifts a steaming coffee mug and smiles.',
  'restaurant-menu-hero':
    "A chef's hands drizzle glossy golden saffron sauce over a seared scallop plated on dark slate, then scatter microgreens as the camera slowly tracks past the steaming dish in warm backlit window light, oil glistening.",
  'fitness-coaching':
    'A male coach with short dark hair and a fitted charcoal training tee demonstrates a slow bodyweight squat in a bright wood-floored studio, then rises and turns to camera mid-rep to cue breathing while a gimbal glides from the wide form-check angle into a clean head-and-shoulders piece.',
  'edtech-explainer':
    'A young woman with curly brown hair in a mustard sweater taps her phone at a sunlit café table, smiling as a glass-card UI insert pushes in on a course card whose progress bar fills and an instructor avatar pops up.',
  'automotive-showroom':
    'On polished showroom concrete under bright diffuse LEDs, a gleaming pearl-white SUV sits beneath brand signage as a slow gimbal walks around its curves, then glides through the open door for a clean dashboard reveal while a salesman in a navy blazer gestures softly in the background.',
  'b2b-keynote':
    'A silver-haired male CEO in a tailored navy blazer strides across a minimal stage, gesturing toward a glowing brand mark as he announces a launch, the camera punching in close before cutting to applauding audience faces in soft ambient haze.',
  'nonprofit-cause':
    'A woman with short gray hair and a worn denim shirt, a longtime community volunteer, kneels in a sunlit garden plot speaking warmly to camera as she lifts a basket of fresh vegetables, then the handheld frame drifts to children running between the rows behind her.',
  'travel-destination':
    'At dawn a drone sweeps over terraced rice fields toward a misty Vietnamese valley, then cuts to an elderly fisherman in a conical hat casting his net across the glassy river, water rippling in golden magic-hour light.',
};
