/**
 * Resolution reconciliation for stitched sequences.
 *
 * Multi-model video selection (#545) lets a single sequence mix per-scene
 * videos generated by different models. Those models do **not** all emit the
 * same pixel dimensions for a given aspect ratio — "16:9" from one model can be
 * 1920×1080 while another returns 1280×1280 — so the per-scene clips come out
 * at different sizes. The Mediabunny stitch/export path assumes uniform inputs,
 * so it must normalize mismatched scenes to a common target.
 *
 * This module is pure arithmetic (no Mediabunny / WebCodecs surface) so the
 * target-resolution and mismatch-detection logic can be unit-tested in
 * isolation. `ConcatenatedVideoSource` probes each scene and feeds the
 * dimensions here.
 */

export type SceneDimensions = {
  width: number;
  height: number;
};

/**
 * Round up to the nearest even integer (minimum 2). H.264 (and most codecs /
 * WebCodecs encoders) require even dimensions for 4:2:0 chroma subsampling, so
 * the normalized target canvas must never be odd.
 */
function toEvenCeil(value: number): number {
  const rounded = Math.ceil(value);
  const even = rounded % 2 === 0 ? rounded : rounded + 1;
  return Math.max(2, even);
}

/**
 * Compute a single target resolution that every scene can be letterboxed into
 * without cropping. We take the bounding box — the max width and max height
 * across all scenes — so the largest scene in each axis is never downscaled and
 * no content is lost; smaller / differently-shaped scenes are `contain`-fit
 * (letter- or pillar-boxed) into the box during stitching.
 *
 * Dimensions are rounded up to even values for codec compatibility.
 *
 * Throws if given an empty list — callers always have at least one scene — or
 * if any scene reports a non-positive / non-finite dimension. A failed probe
 * (0 or NaN) must fail loudly here rather than propagating into a NaN-sized
 * canvas deep in the export pipeline.
 */
export function computeTargetResolution(
  dimensions: SceneDimensions[]
): SceneDimensions {
  if (dimensions.length === 0) {
    throw new Error('computeTargetResolution: at least one scene is required');
  }
  let width = 0;
  let height = 0;
  for (let i = 0; i < dimensions.length; i++) {
    const dim = dimensions[i];
    if (!dim || !isPositiveFinite(dim.width) || !isPositiveFinite(dim.height)) {
      throw new Error(
        `computeTargetResolution: scene ${i} reported invalid dimensions ${dim?.width}×${dim?.height}`
      );
    }
    if (dim.width > width) width = dim.width;
    if (dim.height > height) height = dim.height;
  }
  return { width: toEvenCeil(width), height: toEvenCeil(height) };
}

function isPositiveFinite(value: number): boolean {
  return Number.isFinite(value) && value >= 1;
}

/**
 * True when the scenes resolve to more than one distinct native resolution —
 * i.e. the models disagree on pixel dimensions and the output must be
 * normalized (and the user warned). A single scene, or N scenes that all share
 * the same dimensions, returns `false`.
 */
export function detectMixedResolutions(dimensions: SceneDimensions[]): boolean {
  if (dimensions.length < 2) return false;
  const first = dimensions[0];
  if (!first) return false;
  return dimensions.some(
    (dim) => dim.width !== first.width || dim.height !== first.height
  );
}

/**
 * True when the scenes' aspect ratios differ by more than ~1% — i.e.
 * normalization will letterbox/pillarbox rather than just upscale. Used to
 * pick accurate user-facing copy: same-ratio scenes scale to fill the target
 * frame edge-to-edge, while different-ratio scenes get bars. The tolerance
 * absorbs rounding noise (e.g. 1916×1080 vs 1920×1080) where bars would be
 * invisible anyway.
 */
export function detectMixedAspectRatios(
  dimensions: SceneDimensions[]
): boolean {
  const first = dimensions[0];
  if (!first || dimensions.length < 2) return false;
  const firstRatio = first.width / first.height;
  return dimensions.some(
    (dim) => Math.abs(dim.width / dim.height - firstRatio) / firstRatio > 0.01
  );
}

/**
 * Human-readable summary of the distinct resolutions present, e.g.
 * `"1920×1080, 1280×1280"`. Used in user-facing warnings and error messages.
 */
export function describeResolutions(dimensions: SceneDimensions[]): string {
  const seen = new Set<string>();
  const labels: string[] = [];
  for (const dim of dimensions) {
    const key = `${dim.width}×${dim.height}`;
    if (seen.has(key)) continue;
    seen.add(key);
    labels.push(key);
  }
  return labels.join(', ');
}
