/**
 * Generate endpoint-map.ts for motion models
 *
 * Reads the generated types.gen.ts, zod.gen.ts, and schemas.gen.ts to extract
 * endpoint info, then generates typed maps from endpoint ID → Zod schema and codec.
 *
 * Prompt length limits come from the JSON Schema objects in schemas.gen.ts,
 * imported at runtime — not hardcoded.
 *
 * Usage: bun scripts/generate-motion-endpoint-map.ts
 * (Called automatically by pull-motion-schemas.ts after codegen)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const GENERATED_DIR = join(
  import.meta.dirname,
  '..',
  'src',
  'lib',
  'motion',
  'generated'
);

const MOTION_DIR = join(import.meta.dirname, '..', 'src', 'lib', 'motion');

type EndpointInfo = {
  endpointId: string;
  inputType: string;
  outputType: string;
  zodInputSchema: string;
  jsonSchema: string;
};

function extractEndpoints(): EndpointInfo[] {
  const typesContent = readFileSync(
    join(GENERATED_DIR, 'types.gen.ts'),
    'utf-8'
  );
  const zodContent = readFileSync(join(GENERATED_DIR, 'zod.gen.ts'), 'utf-8');
  const schemasContent = readFileSync(
    join(GENERATED_DIR, 'schemas.gen.ts'),
    'utf-8'
  );
  const endpoints: EndpointInfo[] = [];

  // Match PostXxxData types to extract body type and URL
  const postTypeRegex =
    /export type (Post\w+)Data = \{[\s\S]*?body:\s*(\b\w+\b);?[\s\S]*?url:\s*["']([^"']+)["']/g;

  let match;
  while ((match = postTypeRegex.exec(typesContent)) !== null) {
    const inputType = match[2];
    const urlPath = match[3];
    if (!inputType || !urlPath) continue;

    const endpointId = urlPath.replace(/^\//, '');
    const outputType = inputType.replace(/Input(Type\d+)?$/, 'Output$1');

    // Find matching Zod schema name
    const zodInputSchema = `z${inputType}`;
    if (!zodContent.includes(`export const ${zodInputSchema}`)) {
      console.warn(
        `  Warning: No Zod schema ${zodInputSchema} for ${endpointId}`
      );
      continue;
    }

    // Find matching JSON schema name
    const jsonSchema = `${inputType}Schema`;
    if (!schemasContent.includes(`export const ${jsonSchema}`)) {
      console.warn(`  Warning: No JSON schema ${jsonSchema} for ${endpointId}`);
      continue;
    }

    // Skip non-POST endpoints (status, cancel, etc.)
    if (urlPath.includes('/requests/')) continue;

    endpoints.push({
      endpointId,
      inputType,
      outputType,
      zodInputSchema,
      jsonSchema,
    });
  }

  return endpoints;
}

function generateEndpointMap(endpoints: EndpointInfo[]): string {
  const sorted = [...endpoints].sort((a, b) =>
    a.endpointId.localeCompare(b.endpointId)
  );
  const zodImports = sorted.map((e) => e.zodInputSchema).sort();
  const jsonSchemaImports = sorted.map((e) => e.jsonSchema).sort();

  const jsonSchemaEntries = sorted
    .map((e) => `  ${JSON.stringify(e.endpointId)}: ${e.jsonSchema},`)
    .join('\n');

  const codecEntries = sorted
    .map(
      (e) =>
        `  ${JSON.stringify(e.endpointId)}: motionTransform(${e.zodInputSchema}, ${e.jsonSchema}),`
    )
    .join('\n');

  const jsonSchemaUnion = jsonSchemaImports
    .map((s) => `typeof ${s}`)
    .join(' | ');

  return `// AUTO-GENERATED by scripts/generate-motion-endpoint-map.ts — do not edit
// Endpoint ID → generated Zod schema and codec mapping for motion models

import { z } from 'zod';

import { motionTransform } from './motion-transform';

import {
${zodImports.map((s) => `  ${s},`).join('\n')}
} from './generated/zod.gen';

import {
${jsonSchemaImports.map((s) => `  ${s},`).join('\n')}
} from './generated/schemas.gen';

export type MotionJSONSchema = ${jsonSchemaUnion};

export const MOTION_INPUT_SCHEMAS = {
${sorted.map((e) => `  ${JSON.stringify(e.endpointId)}: ${e.zodInputSchema},`).join('\n')}
};

export type MotionEndpointId = keyof typeof MOTION_INPUT_SCHEMAS;

/**
 * Input payload for a given motion endpoint. Generated API surface — kept
 * exported even while unused so consumers of new endpoints can adopt it.
 * @public
 */
export type MotionInputFor<T extends MotionEndpointId> = z.infer<
  (typeof MOTION_INPUT_SCHEMAS)[T]
>;

export const MOTION_JSON_SCHEMAS = {
${jsonSchemaEntries}
} satisfies Record<MotionEndpointId, MotionJSONSchema>;

export const MOTION_TRANSFORMS = {
${codecEntries}
};
`;
}

function main() {
  console.log('Generating motion endpoint map...\n');

  const endpoints = extractEndpoints();
  console.log(`  Found ${endpoints.length} endpoints:`);
  for (const e of endpoints) {
    console.log(`    ${e.endpointId} → ${e.zodInputSchema} + ${e.jsonSchema}`);
  }

  const endpointMapPath = join(MOTION_DIR, 'endpoint-map.ts');
  writeFileSync(endpointMapPath, generateEndpointMap(endpoints));
  console.log(`\n  Written ${endpointMapPath}`);
}

main();
