/**
 * Pull prompts from Langfuse and write to local-prompts.ts
 *
 * Usage: bun scripts/pull-prompts.ts
 *
 * Requires LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY (and optionally LANGFUSE_BASE_URL)
 * to be set in .env.local or environment.
 */

import { LangfuseClient } from '@langfuse/client';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

const OUTPUT_PATH = resolve(
  import.meta.dirname,
  '../src/lib/prompts/workflow-prompts.ts'
);

type ChatMessage = {
  role: 'system' | 'user' | 'assistant';
  content: string;
};

async function main() {
  const langfuse = new LangfuseClient();
  const prompts = await langfuse.api.prompts.list({ limit: 100 });

  console.log(`Found ${prompts.data.length} prompts in Langfuse\n`);

  const textPrompts: Record<string, string> = {};
  const chatPrompts: Record<string, ChatMessage[]> = {};

  for (const meta of prompts.data) {
    const name = meta.name;
    const type = meta.type;

    try {
      if (type === 'text') {
        const prompt = await langfuse.prompt.get(name, { type: 'text' });
        textPrompts[name] = prompt.prompt;
        console.log(`  [text] ${name} (${prompt.prompt.length} chars)`);
      } else {
        const prompt = await langfuse.prompt.get(name, { type: 'chat' });
        // Langfuse chat prompts return an array of messages (or placeholders)
        const validRoles: Set<string> = new Set([
          'system',
          'user',
          'assistant',
        ]);
        const rawMessages = prompt.prompt;
        const messages: ChatMessage[] = [];
        for (const m of rawMessages) {
          if ('role' in m && 'content' in m && validRoles.has(m.role)) {
            const role =
              m.role === 'system'
                ? 'system'
                : m.role === 'user'
                  ? 'user'
                  : 'assistant';
            messages.push({ role, content: m.content });
          }
        }
        chatPrompts[name] = messages;
        console.log(`  [chat] ${name} (${messages.length} messages)`);
      }
    } catch (error) {
      console.error(
        `  [error] ${name}: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }

  const textCount = Object.keys(textPrompts).length;
  const chatCount = Object.keys(chatPrompts).length;

  const escapeBacktick = (s: string) =>
    s.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  const textEntries = Object.entries(textPrompts)
    .map(([name, prompt]) => `  '${name}': \`${escapeBacktick(prompt)}\`,`)
    .join('\n\n');

  const chatEntries = Object.entries(chatPrompts)
    .map(([name, messages]) => {
      const msgs = messages
        .map(
          (m) =>
            `    { role: '${m.role}', content: \`${escapeBacktick(m.content)}\` },`
        )
        .join('\n');
      return `  '${name}': [\n${msgs}\n  ],`;
    })
    .join('\n\n');

  const fileContent = `/**
 * Local Prompt Registry
 *
 * Auto-generated by \`bun scripts/pull-prompts.ts\`
 * These prompts are used as fallbacks when Langfuse is not configured.
 *
 * To update: run \`bun scripts/pull-prompts.ts\` with Langfuse credentials set.
 */

export type ChatMessage = {
  role: 'system' | 'user' | 'assistant';
  content: string;
};

/**
 * Text prompts (used via getPrompt → system message for streaming calls)
 */
export const WORKFLOW_TEXT_PROMPTS: Record<string, string> = {
${textEntries}
};

/**
 * Chat prompts (used via getChatPrompt → durable workflow calls)
 */
export const WORKFLOW_CHAT_PROMPTS: Record<string, ChatMessage[]> = {
${chatEntries}
};
`;

  writeFileSync(OUTPUT_PATH, fileContent);
  console.log(
    `\\nWrote ${textCount} text + ${chatCount} chat prompts to ${OUTPUT_PATH}`
  );
}

main().catch((error) => {
  console.error(
    'Failed to pull prompts:',
    error instanceof Error ? error.message : String(error)
  );
  process.exit(1);
});
